version_info_list:
  - latest version
  - 9.0.0
  - 8.9.3
  - 8.9.0
  - 8.8.7
  - 8.8.5
  - 8.8.3
  - 8.8.0
  - 8.6.3
  - 8.6.1
  - 8.6.0
  - 8.4.0
  - 8.2.5
  - 8.2.3
  - 8.2.1
  - 8.2.0
  - 8.1.3
  - 8.1.2
  - 8.1.0
  - 8.0.0
  - 7.6.0
  - 7.5.0 

version_info_list_desktop:
  - latest version
  - 9.0.0
  - 8.8.0
  - 8.6.0
  - 8.4.0
  - 8.2.0
  - 8.1.2
  - 8.1.0
  - 8.0.0
  - 7.6.0
  - 7.5.0

version_info_list_mobile:
  - latest version
  - 9.0.0
  - 8.9.3
  - 8.9.0
  - 8.8.0
  - 8.6.0
  - 8.4.0
  - 8.2.1
  - 8.2.0
  - 8.1.2
  - 8.1.0
  - 8.0.0
  - 7.6.0
  - 7.5.0

version_info_list_js:
  - latest version
  - 9.0.0
  - 8.8.7
  - 8.8.5
  - 8.8.3
  - 8.8.0
  - 8.6.3
  - 8.6.1
  - 8.6.0
  - 8.4.0
  - 8.2.5
  - 8.2.3
  - 8.2.1
  - 8.2.0
  - 8.1.3
  - 8.1.2
  - 8.1.0
  - 8.0.0
  - 7.6.0
  - 7.5.0
