useGroupedVersion: true

version_info_list_algorithm:
  - value: latest version
  - value: 10.x
    child:
      - 10.5.2100
      - 10.2.0
      - 10.0.21
      - 10.0.20
      - 10.0.10
      - 10.0.0
  - value: 9.x
    child:
      - 9.6.42
      - 9.6.40
      - 9.6.33
      - 9.6.32
      - 9.6.31
      - 9.6.30
      - 9.6.20
      - 9.6.10
      - 9.6.0
      - 9.4.0
      - 9.2.0
      - 9.0.0
  - value: 8.x
    child:
      - 8.8.0
      - 8.6.0
      - 8.4.0
      - 8.2.0
      - 8.1.2
      - 8.1.0
      - 8.0.0
  - value: 7.x
    child:
      - 7.6.0
      - 7.5.0
